-- I don't know what's happening with the OIDS=FALSE. That line was generated by the online database-builder tool

CREATE TABLE "users" (
	"id" serial NOT NULL,
	"username" character varying NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "zipcodes" (
	"id" serial NOT NULL,
	"zipcodes" int NOT NULL,
	CONSTRAINT zipcodes_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "users_zipcodes" (
	"id" serial NOT NULL,
	"user_id" serial NOT NULL,
	"zipcode_id" serial NOT NULL,
	"weather_id" int NOT NULL,
	CONSTRAINT users_zipcodes_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "weather" (
	"id" serial NOT NULL,
	"coord_lon" int NOT NULL,
	"coord_lat" int NOT NULL,
	"weather_id" int NOT NULL,
	"weather_main" varchar NOT NULL,
	"weather_description" varchar NOT NULL,
	"main_temp" int NOT NULL,
	"main_pressure" int NOT NULL,
	"main_humidity" int NOT NULL,
	"main_temp_min" int NOT NULL,
	"main_temp_max" int NOT NULL,
	"main_sea_level" int,
	"main_grnd_level" int,
	"wind_speed" int NOT NULL,
	"wind_deg" int NOT NULL,
	"clouds_all" int NOT NULL,
	"rain_3h" int NOT NULL,
	"snow_3h" int NOT NULL,
	"dt" int NOT NULL,
	"sys_country" varchar NOT NULL,
	"sys_sunrise" int NOT NULL,
	"sys_sunset" int NOT NULL,
	"city_id" int NOT NULL,
	"city_name" varchar NOT NULL,
	"date_added" DATE NOT NULL,
	CONSTRAINT weather_pk PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);





ALTER TABLE "users_zipcodes" ADD CONSTRAINT "users_zipcodes_fk0" FOREIGN KEY ("user_id") REFERENCES "users"("id");
ALTER TABLE "users_zipcodes" ADD CONSTRAINT "users_zipcodes_fk1" FOREIGN KEY ("zipcode_id") REFERENCES "zipcodes"("id");
ALTER TABLE "users_zipcodes" ADD CONSTRAINT "users_zipcodes_fk2" FOREIGN KEY ("weather_id") REFERENCES "weather"("id");


